// Autogenerated by Frugal Compiler (2.23.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package subdir_include

import (
	"github.com/Workiva/frugal/lib/gopherjs/frugal"
)

// A is a frual serializable object.
type A struct {
}

// NewA constructs a A.
func NewA() *A {
	return &A{
		// TODO: default values

	}
}

// Unpack deserializes A objects.
func (p *A) Unpack(prot frugal.Protocol) {
	prot.UnpackStructBegin("A")
	for typeID, id := prot.UnpackFieldBegin(); typeID != frugal.STOP; typeID, id = prot.UnpackFieldBegin() {
		switch id {
		default:
			prot.Skip(typeID)
		}
		prot.UnpackFieldEnd()
	}
	prot.UnpackStructEnd()
}

// Pack serializes A objects.
func (p *A) Pack(prot frugal.Protocol) {
	prot.PackStructBegin("A")
	prot.PackFieldStop()
	prot.PackStructEnd()
}
