// Autogenerated by Frugal Compiler (2.23.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package validStructs

import (
	"github.com/Workiva/frugal/lib/gopherjs/frugal"
)

// Thing is a frual serializable object.
type Thing struct {
}

// NewThing constructs a Thing.
func NewThing() *Thing {
	return &Thing{
		// TODO: default values

	}
}

// Unpack deserializes Thing objects.
func (p *Thing) Unpack(prot frugal.Protocol) {
	prot.UnpackStructBegin("Thing")
	for typeID, id := prot.UnpackFieldBegin(); typeID != frugal.STOP; typeID, id = prot.UnpackFieldBegin() {
		switch id {
		default:
			prot.Skip(typeID)
		}
		prot.UnpackFieldEnd()
	}
	prot.UnpackStructEnd()
}

// Pack serializes Thing objects.
func (p *Thing) Pack(prot frugal.Protocol) {
	prot.PackStructBegin("Thing")
	prot.PackFieldStop()
	prot.PackStructEnd()
}
